# syntax=docker/dockerfile:1
FROM python:{{ python_version }}-slim
WORKDIR /app
COPY . .
RUN pip install -U pip && pip install -e .
EXPOSE 8000
CMD ["uvicorn", "{{ package_name }}.main:app", "--host", "0.0.0.0", "--port", "8000"]